# frozen_string_literal: true

source 'https://rubygems.org'

git_source(:github) { |repo_name| "https://github.com/#{repo_name}" }

gem 'activemodel'
gem 'factory_bot'
gem 'faraday', '>= 2.2'
gem 'pry'
gem 'rspec'
gem 'webmock'
